security {
    policies {
        default-policy {
            permit-all;
        }
    }
    zones {
        security-zone UNTRUST {
            host-inbound-traffic {
                system-services {
                    all;
                }
                protocols {
                    all;
                }
            }
            interfaces {
                ge-0/0/0.0;
            }
        }
        security-zone TRUST {
            host-inbound-traffic {
                system-services {
                    all;
                }
                protocols {
                    all;
                }
            }
            interfaces {
                ge-0/0/1.0;
            }
        }
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 100.64.12.2/24;
            }
        }
    }
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 192.168.2.1/24;
            }
        }
    }
}
policy-options {
    policy-statement direct-routes {
        from protocol direct;
        then accept;
    }
}
protocols {
    bgp {
        group clab {
            type external;
            export direct-routes;
            local-as 65002;
            neighbor 100.64.12.1 {
                peer-as 65001;
            }
        }
    }
}
